// generated by rust-bindgen 0.57.0, hacked down manually

pub const ACMIRecGenPosition: ::std::os::raw::c_uint = 0;
pub const ACMIRecMissilePosition: ::std::os::raw::c_uint = 1;
pub const ACMIRecFeaturePosition: ::std::os::raw::c_uint = 2;
pub const ACMIRecAircraftPosition: ::std::os::raw::c_uint = 3;
pub const ACMIRecTracerStart: ::std::os::raw::c_uint = 4;
pub const ACMIRecStationarySfx: ::std::os::raw::c_uint = 5;
pub const ACMIRecMovingSfx: ::std::os::raw::c_uint = 6;
pub const ACMIRecSwitch: ::std::os::raw::c_uint = 7;
pub const ACMIRecDOF: ::std::os::raw::c_uint = 8;
pub const ACMIRecChaffPosition: ::std::os::raw::c_uint = 9;
pub const ACMIRecFlarePosition: ::std::os::raw::c_uint = 10;
pub const ACMIRecTodOffset: ::std::os::raw::c_uint = 11;
pub const ACMIRecFeatureStatus: ::std::os::raw::c_uint = 12;
pub const ACMICallsignList: ::std::os::raw::c_uint = 13;
pub const ACMIRecMaxTypes: ::std::os::raw::c_uint = 14;

#[repr(C, packed)]
#[derive(Debug, Copy, Clone)]
pub struct ACMIRecHeader {
    pub type_: u8,
    pub time: f32,
}


#[repr(C, packed)]
#[derive(Debug, Copy, Clone)]
pub struct ACMIGenPositionData {
    pub type_: i32,
    pub uniqueID: i32,
    pub x: f32,
    pub y: f32,
    pub z: f32,
    pub yaw: f32,
    pub pitch: f32,
    pub roll: f32,
}

#[repr(C, packed)]
#[derive(Debug, Copy, Clone)]
pub struct ACMIFeaturePositionData {
    pub type_: i32,
    pub uniqueID: i32,
    pub leadUniqueID: i32,
    pub slot: i32,
    pub specialFlags: i32,
    pub x: f32,
    pub y: f32,
    pub z: f32,
    pub yaw: f32,
    pub pitch: f32,
    pub roll: f32,
}

#[repr(C, packed)]
#[derive(Debug, Copy, Clone)]
pub struct ACMISwitchData {
    pub type_: i32,
    pub uniqueID: i32,
    pub switchNum: i32,
    pub switchVal: i32,
    pub prevSwitchVal: i32,
}

#[repr(C, packed)]
#[derive(Debug, Copy, Clone)]
pub struct ACMIFeatureStatusData {
    pub uniqueID: i32,
    pub newStatus: i32,
    pub prevStatus: i32,
}

#[repr(C, packed)]
#[derive(Debug, Copy, Clone)]
pub struct ACMIDOFData {
    pub type_: i32,
    pub uniqueID: i32,
    pub DOFNum: i32,
    pub DOFVal: f32,
    pub prevDOFVal: f32,
}

#[repr(C, packed)]
#[derive(Debug, Copy, Clone)]
pub struct ACMITracerStartData {
    pub x: f32,
    pub y: f32,
    pub z: f32,
    pub dx: f32,
    pub dy: f32,
    pub dz: f32,
}

#[repr(C, packed)]
#[derive(Debug, Copy, Clone)]
pub struct ACMIStationarySfxData {
    pub type_: i32,
    pub x: f32,
    pub y: f32,
    pub z: f32,
    pub timeToLive: f32,
    pub scale: f32,
}

#[repr(C, packed)]
#[derive(Debug, Copy, Clone)]
pub struct ACMIMovingSfxData {
    pub type_: i32,
    pub user: i32,
    pub flags: i32,
    pub x: f32,
    pub y: f32,
    pub z: f32,
    pub dx: f32,
    pub dy: f32,
    pub dz: f32,
    pub timeToLive: f32,
    pub scale: f32,
}

#[repr(C, packed)]
#[derive(Debug, Copy, Clone)]
pub struct ACMIMovingSfxRecord {
    pub hdr: ACMIRecHeader,
    pub data: ACMIMovingSfxData,
}

#[repr(C, )]
#[derive(Debug, Copy, Clone)]
pub struct ACMIStationarySfxRecord {
    pub hdr: ACMIRecHeader,
    pub data: ACMIStationarySfxData,
}

#[repr(C, packed)]
#[derive(Debug, Copy, Clone)]
pub struct ACMIGenPositionRecord {
    pub hdr: ACMIRecHeader,
    pub data: ACMIGenPositionData,
}

#[repr(C, packed)]
#[derive(Debug, Copy, Clone)]
pub struct ACMIMissilePositionRecord {
    pub hdr: ACMIRecHeader,
    pub data: ACMIGenPositionData,
}

#[repr(C, packed)]
#[derive(Debug, Copy, Clone)]
pub struct ACMITodOffsetRecord {
    pub hdr: ACMIRecHeader,
}

#[repr(C, packed)]
#[derive(Debug, Copy, Clone)]
pub struct ACMIChaffPositionRecord {
    pub hdr: ACMIRecHeader,
    pub data: ACMIGenPositionData,
}

#[repr(C, packed)]
#[derive(Debug, Copy, Clone)]
pub struct ACMIFlarePositionRecord {
    pub hdr: ACMIRecHeader,
    pub data: ACMIGenPositionData,
}

#[repr(C, packed)]
#[derive(Debug, Copy, Clone)]
pub struct ACMIAircraftPositionRecord {
    pub hdr: ACMIRecHeader,
    pub data: ACMIGenPositionData,
    pub RadarTarget: i32,
}

#[repr(C, packed)]
#[derive(Debug, Copy, Clone)]
pub struct ACMIFeaturePositionRecord {
    pub hdr: ACMIRecHeader,
    pub data: ACMIFeaturePositionData,
}

#[repr(C, packed)]
#[derive(Debug, Copy, Clone)]
pub struct ACMIFeatureStatusRecord {
    pub hdr: ACMIRecHeader,
    pub data: ACMIFeatureStatusData,
}

#[repr(C, packed)]
#[derive(Debug, Copy, Clone)]
pub struct ACMITracerStartRecord {
    pub hdr: ACMIRecHeader,
    pub data: ACMITracerStartData,
}

#[repr(C, packed)]
#[derive(Debug, Copy, Clone)]
pub struct ACMISwitchRecord {
    pub hdr: ACMIRecHeader,
    pub data: ACMISwitchData,
}

#[repr(C, packed)]
#[derive(Debug, Copy, Clone)]
pub struct ACMIDOFRecord {
    pub hdr: ACMIRecHeader,
    pub data: ACMIDOFData,
}

#[repr(C, packed)]
#[derive(Debug, Copy, Clone)]
pub struct ACMI_CallRec {
    pub label: [::std::os::raw::c_char; 16usize],
    pub teamColor: i32,
}
